### ISSUE TITLE
Unknown props warning

### ISSUE THREAD

**Issue by Radivarig** [moodysalem/react-fastclick#2]
React warns about unknown props passed:

```
Warning: Unknown props `threshold`, `timeThreshold` on <span> tag. Remove these props from the element.
```

in this case [here #L212](https://github.com/moodysalem/react-fastclick/blob/771026b33812308a28ba6b95341152144005997d/index.js#L212), where props are assigned to span.

**Comment by moodysalem** [comment]
Thanks for the report-I went ahead and updated to the module for ES6 and fixed some issues due to me being less familiar with webpack, karma, npm, etc

~~FYI you shouldn't really need this module anymore with iOS 9.3 and Android chrome both handling short taps better as long as you have the appropriate meta viewport tag~~
